<?php
$this->headScript()
  ->prependFile($this->basePath('js/test/sections/home.js'))
  ->prependFile($this->basePath('js/test/widgets/gridFirst.js'))
  ->prependFile($this->basePath('js/test/test.js'));
?>
<script type="text/javascript">
    Ext.onReady(function() {
        Ext.create({xtype: "test-panel-home"});
    });
</script>

<div style="margin: auto;width: 80%"  id="test"></div>
<br>
<div style="margin: auto;width: 80%"  id="test-grid"></div>